#! /usr/bin/bash

DB="prova5"

#~/Downloads/solr-8.4.1/bin/solr create -c biblioteca

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"nome_cognome","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"ruolo","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"evento","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema


curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"committente","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"ricorrenza","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"dedica","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"dimensioni","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"curatore","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"categoria","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"tecnica","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema


curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"data","type":"pdate","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"tipo_delibera","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"argomento_breve","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"testo","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"unanimita","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"favorevoli","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"contrari","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"astenuti","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"straordinaria","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"capitolo","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"pagina","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema
curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"num_contestuale","type":"pint","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8985/solr/archivio/schema


curl -X POST -H 'Content-type:application/json' --data-binary '{"delete-field" : { "name":"id" }}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"codice_archivio","type":"string","docValues":false,"multiValued":false,"indexed":true,"stored":true, required:true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"update-field":{"name":"anno","type":"pint","docValues":true,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/prova5/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"private","type":"pint","docValues":true,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"cdd","type":"string","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"timestamp","type":"pdate","docValues":false,"multiValued":false,"indexed":true,"stored":true,"default":"NOW"}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"tipologia","type":"string","docValues":false,"multiValued":false,"indexed":true,"stored":true, required:true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"titolo","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true, required:true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"sottotitolo","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"prima_responsabilita","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"altre_responsabilita","type":"text_general","multiValued":false,"docValues":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"soggetto","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"luogo","type":"string","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"edizione","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"ente","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"serie","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"descrizione","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"note","type":"text_general","docValues":false,"multiValued":false,"indexed":true,"stored":true}}' http://localhost:8983/solr/archivio/schema

#curl 'http://localhost:8983/solr/biblioteca/update?commit=true' --data-binary @example/exampledocs/BIBLIOTECA\ FALASSI.csv -H 'Content-type:application/csv'

# pdates, plongs, text_general multivalued false



        "Content-Length":[4789970],
        "Content-Type":["application/pdf"],
        "Creation-Date":["2020-03-22T11:48:54Z"],
        "resourceName":["197202003.jpg"],
        "codice_archivio":"SON.00001",
        "tipologia":"SONETTO",
        "note":"Questa e` una prova",
        "text":["\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nFLASH SULL’INCONTENIBILE GIOIA DELL’IMMEDIATO DOPO - CORSA \n\n  \nUn quartetto da quadretto \n\n  E giovane: è la prima volta che vede lIstrice primo: il pianto scioglie \nla sua passione, simbolo della gioventù istriciaiola \n\n  \nFiguranti ..... sfigurati dalla non repressa passione\n\n\n"],
        "dc_format":["application/pdf; version=1.5"],
        "dcterms_created":["2020-03-22T11:48:54Z"],
        "meta_creation-date":["2020-03-22T11:48:54Z"],
        "pdf_PDFVersion":[1.5],
        "pdf_charsPerPage":[271],
        "pdf_docinfo_created":["2020-03-22T11:48:54Z"],
        "pdf_docinfo_producer":["Tesseract 4.1.1"],
        "pdf_encrypted":[false],
        "pdf_hasXFA":[false],
        "pdf_hasXMP":[false],
        "pdf_unmappedUnicodeCharsPerPage":[0],
        "xmpTPg_NPages":[1],
        "timestamp":"2020-03-22T12:00:17.014Z",
        "_version_":1661865471004114944}]
